### ISSUE TITLE
Incomplete dataset on Zenodo

### ISSUE THREAD

**Issue by ghost** [polimi-ispl/larsnet#2]
Congrats for your participation at ISMIR2023 SDX workshop !

The link provided https://zenodo.org/records/7882857 as part 2 of the dataset leads to 404 error.
When will missing parts of the dataset be uploaded or link be fixed ?
Thanks !

**Comment by riccardogiampiccolo** [comment]
We have now uploaded the full dataset on Zenodo. Part 2 is thus now available!
